title: "Zhenbang Zhang"
email: "zhangzhenbang2021@gmail.com"
description: "Zhenbang Zhang's academic homepage in machine learning, computer vision, 3D/4D AI, biomedical imaging, and connectomics."
url: "https://zhangzhenbang2021.github.io"
baseurl: ""
repository: "zhangzhenbang2021/zhangzhenbang2021.github.io"

markdown: kramdown

plugins:
  - jekyll-sitemap

collections:
  publications:
    output: false
  news:
    output: false

kramdown:
  input: GFM
